# Generated by Django 5.0 on 2023-12-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_baby_date_of_birth_alter_baby_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='amount',
            field=models.FloatField(verbose_name='Amount (ml)'),
        ),
    ]
