# Generated by Django 5.0 on 2023-12-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_feeding_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sleep Date')),
                ('startTime', models.TimeField(verbose_name='Start Time')),
                ('endTime', models.TimeField(verbose_name='End Time')),
                ('type', models.CharField(choices=[('n', 'Nap'), ('s', 'Sleep')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Change Date')),
                ('time', models.TimeField(verbose_name='Change Time')),
                ('type', models.CharField(choices=[('1', 'Pee'), ('2', 'Poo')], default='1', max_length=1)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.baby')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
